### ISSUE TITLE
Output from test confusing

### ISSUE THREAD

**Issue by bhalonen** [markhalonen/chester#1]
After running the instructions in the README, I got this output:
```
Brents-MBP-3:MarksStuff brent$ ./snapper test
0 : passed
```

Which is a bit confusing.

**Comment by bhalonen** [comment]
I would change it to "Test 1 : passed"

https://github.com/markhalonen/snapper/blob/44e5c5d3c158076e883db5f2a44ab92c6f1d60f1/app.go#L219

**Comment by markhalonen** [comment]
Dad had similar feedback. I changed the output format, and updating the snapper tests on snapper was a breeze.
